apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.services.sync.name }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
  {{- with .Values.front.services.sync.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.front.services.sync.type }}
  ports:
    - port: {{ .Values.front.services.sync.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "front.selectorLabels" . | nindent 4 }}
