{{- if .Values.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.fullname" . }}-config
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
{{- end }}
