{{- if not .Values.db.database.existingSecret -}}
{{- if .Values.db.database.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.database.secretName" . }}
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.db.database.existingSecretPasswordKey }}: {{ .Values.db.database.password | b64enc | quote }}
{{- end -}}
{{- end -}}
