{{- if not .Values.encryption.existingSecret -}}
{{- $secretName := include "affine.encryption.secretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existing }}
  {{ .Values.encryption.existingSecretKey }}: {{ index $existing.data .Values.encryption.existingSecretKey }}
  {{- else }}
  {{ .Values.encryption.existingSecretKey }}: {{ genPrivateKey "ecdsa" | b64enc | quote }}
  {{- end }}
{{- end -}}
