{{- if not .Values.db.redis.existingSecret -}}
{{- if .Values.db.redis.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.redis.secretName" . }}
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.db.redis.existingSecretPasswordKey }}: {{ .Values.db.redis.password | b64enc | quote }}
{{- end -}}
{{- end -}}
