{{- if and .Values.webhook.httpRoute.enabled (eq .Values.db.type "postgresdb") (eq .Values.webhook.mode "queue") -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-webhook" (include "n8n.names.fullname" .) }}
  labels:
    {{- include "n8n.labels.component" (dict "context" . "component" "webhook") | nindent 4 }}
    {{- with .Values.webhook.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webhook.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webhook.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml .Values.webhook.httpRoute.parentRefs | nindent 4 }}
  {{- end }}
  {{- if .Values.webhook.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.webhook.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path: { type: PathPrefix, value: /webhook }
        - path: { type: PathPrefix, value: /webhook-waiting }
        - path: { type: PathPrefix, value: /form }
        - path: { type: PathPrefix, value: /form-waiting }
      backendRefs:
        - name: {{ printf "%s-webhook" (include "n8n.names.fullname" .) }}
          port: {{ .Values.global.service.port }}
    {{- if .Values.webhook.mcp.enabled }}
    - matches:
        - path: { type: PathPrefix, value: /mcp }
      backendRefs:
        - name: {{ include "n8n.mcp-webhook.serviceName" . }}
          port: {{ .Values.global.service.port }}
    {{- end }}
{{- end }}
