{{- if and .Values.webhook.pdb.enabled (eq .Values.db.type "postgresdb") (eq .Values.webhook.mode "queue") (not .Values.webhook.allNodes) (or .Values.webhook.autoscaling.enabled (gt (int .Values.webhook.count) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "n8n.names.fullname" . }}-webhook
  labels:
    {{- include "n8n.labels.component" (dict "context" . "component" "webhook") | nindent 4 }}
spec:
  {{- if .Values.webhook.pdb.minAvailable }}
  minAvailable: {{ .Values.webhook.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.webhook.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.webhook.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.labels.matchLabelsComponent" (dict "context" . "component" "webhook") | nindent 6 }}
{{- end }}
