{{- if .Values.main.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "n8n.names.fullname" . }}
  labels:
    {{- include "n8n.labels.component" (dict "context" . "component" "main") | nindent 4 }}
    {{- with .Values.main.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.main.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.main.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml .Values.main.httpRoute.parentRefs | nindent 4 }}
  {{- end }}
  {{- if .Values.main.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.main.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path: { type: PathPrefix, value: / }
      backendRefs:
        - name: {{ include "n8n.names.fullname" . }}
          port: {{ .Values.global.service.port }}
{{- end }}
