{{- if and .Values.main.pdb.enabled (or (gt (int .Values.main.count) 1) (not (eq .Values.global.strategy.type "Recreate"))) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "n8n.names.fullname" . }}
  labels:
    {{- include "n8n.labels.component" (dict "context" . "component" "main") | nindent 4 }}
spec:
  {{- if .Values.main.pdb.minAvailable }}
  minAvailable: {{ .Values.main.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.main.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.main.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.labels.matchLabelsComponent" (dict "context" . "component" "main") | nindent 6 }}
{{- end }}
