{{- if or (.Values.main.forceToUseStatefulset) (and .Values.main.persistence.enabled (gt (int .Values.main.count) 1) (not .Values.main.persistence.existingClaim) (eq .Values.main.persistence.accessMode "ReadWriteOnce")) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "n8n.names.fullname" . }}
  labels:
    {{- include "n8n.labels.component" (dict "context" . "component" "main") | nindent 4 }}
spec:
  {{- if .Values.global.service.enabled }}
  serviceName: {{ include "n8n.names.fullname" . }}-headless
  {{- end }}
  replicas: {{ .Values.main.count }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "n8n.labels.matchLabelsComponent" (dict "context" . "component" "main") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if eq .Values.taskRunners.mode "external" }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.nodes.external.packages }}
        checksum/packages: {{ (join "," .Values.nodes.external.packages) | sha256sum }}
      {{- end }}
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8n.labels.component" (dict "context" . "component" "main") | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "n8n.images.pullSecrets" (dict "images" (list .Values.main.image .Values.nodes.initContainer.image .Values.taskRunners.image) "global" .Values.global) | nindent 6 }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml (default .Values.global.podSecurityContext .Values.main.podSecurityContext) | nindent 8 }}
      {{- with .Values.main.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.main.runtimeClassName }}
      runtimeClassName: {{ .Values.main.runtimeClassName }}
      {{- end }}
      {{- if or .Values.main.initContainers .Values.nodes.external.packages }}
      initContainers:
      {{- end }}
        {{- if .Values.nodes.external.packages }}
        - name: npm-install
          securityContext:
            {{- toYaml (default .Values.global.containerSecurityContext .Values.main.securityContext) | nindent 12 }}
          image: {{ include "n8n.images.image" (dict "imageRoot" .Values.nodes.initContainer.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.nodes.initContainer.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{- include "n8n.npmInstallScript" . | nindent 14 }}
          env:
            {{- include "n8n.env" . | nindent 12 }}
          volumeMounts:
            {{- if .Values.npmRegistry.enabled }}
            - name: npmrc
              mountPath: "/home/node/.npmrc"
              subPath: {{ (default "npmrc" .Values.npmRegistry.secretKey) | quote }}
              readOnly: true
            {{- end }}
            - name: {{ default "node-modules" .Values.main.persistence.volumeName }}
              mountPath: "/npmdata"
              readOnly: false
            - name: community-node-modules
              mountPath: "/nodesdata/nodes"
              readOnly: false
          {{- with .Values.nodes.initContainer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.main.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "n8n.names.name" . }}-main
          securityContext:
            {{- toYaml (default .Values.global.containerSecurityContext .Values.main.securityContext) | nindent 12 }}
          image: {{ include "n8n.images.image" (dict "imageRoot" .Values.main.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.main.image.pullPolicy }}
        {{- if and .Values.license.enabled (or (ne .Values.license.activationKey "") (ne .Values.license.existingActivationKeySecret "")) }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - "n8n license:info && n8n"
        {{- end }}
          ports:
            - name: {{ .Values.global.service.name }}
              containerPort: {{ .Values.global.service.port }}
              protocol: TCP
          livenessProbe:
            {{- $rootLiveness := .Values.livenessProbe | default dict }}
            {{- $mainLiveness := .Values.main.livenessProbe | default dict }}
            {{- toYaml (merge $mainLiveness $rootLiveness) | nindent 12 }}
          readinessProbe:
            {{- $rootReadiness := .Values.readinessProbe | default dict }}
            {{- $mainReadiness := .Values.main.readinessProbe | default dict }}
            {{- toYaml (merge $mainReadiness $rootReadiness) | nindent 12 }}
          resources:
            {{- toYaml (default .Values.global.resources .Values.main.resources) | nindent 12 }}
          env:
          {{- if eq .Values.taskRunners.mode "external" }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.names.fullname" . }}-task-runners-secret
                  key: auth-token
          {{- end }}
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: NODE_ENV
              value: production
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_PORT
              value: {{ .Values.global.service.port | quote }}
            - name: N8N_DEFAULT_LOCALE
              value: {{ .Values.defaultLocale | quote }}
            - name: GENERIC_TIMEZONE
              value: {{ .Values.timezone | quote }}
            - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
              value: {{ .Values.gracefulShutdownTimeout | quote }}
          {{- if eq .Values.db.type "postgresdb" }}
            - name: DB_POSTGRESDB_USER
              value: {{ include "n8n.postgresql.username" . }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.postgresql.fullname" .) .Values.db.postgresdb.existingSecret }}
                  key: postgres-password
                  optional: true
            {{- if eq .Values.worker.mode "queue" }}
            - name: QUEUE_BULL_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.redis.fullname" .) .Values.db.redis.existingSecret }}
                  key: redis-username
                  optional: true
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "n8n.redis.fullname" .) .Values.db.redis.existingSecret }}
                  key: redis-password
                  optional: true
            {{- end }}
          {{- end }}
          {{- if .Values.webhook.url }}
            - name: WEBHOOK_URL
              value: {{ .Values.webhook.url | quote }}
          {{- end }}

          {{- if gt (int .Values.main.count) 1 }}
            - name: N8N_MULTI_MAIN_SETUP_ENABLED
              value: "true"
          {{- end }}
          {{- if has "s3" .Values.binaryData.availableModes }}
            - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-s3-secret" (include "n8n.names.fullname" .)) .Values.binaryData.s3.existingSecret }}
                  key: access-key-id
            - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-s3-secret" (include "n8n.names.fullname" .)) .Values.binaryData.s3.existingSecret }}
                  key: secret-access-key
          {{- end }}
          {{- if eq .Values.taskRunners.mode "internal" }}
          {{- include "n8n.runners.env" . | nindent 12 }}
          {{- end }}
          {{- range $key, $value := (default .Values.global.extraEnvVars .Values.main.extraEnvVars) }}
            - name: {{ upper $key }}
              value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-database-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-logging-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-diagnostics-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-version-notifications-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-public-api-configmap
          {{- if and (eq .Values.db.type "postgresdb") (or (eq .Values.worker.mode "queue") (eq .Values.webhook.mode "queue")) }}
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-queue-configmap
          {{- end }}
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-workflow-history-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-task-broker-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-metrics-configmap
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-binary-data-configmap
          {{- if .Values.license.enabled }}
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-license-configmap
            - secretRef:
                name: {{ default (printf "%s-license-activation-key" (include "n8n.names.fullname" .)) .Values.license.existingActivationKeySecret }}
          {{- end }}
            - secretRef:
                name: {{ default (printf "%s-encryption-key-secret-v2" (include "n8n.names.fullname" .)) .Values.existingEncryptionKeySecret }}
          {{- range (default .Values.extraSecretNamesForEnvFrom .Values.main.extraSecretNamesForEnvFrom) }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- if or (eq (include "n8n.main.hasVolumeMounts" .) "true") (eq .Values.taskRunners.mode "internal") }}
          volumeMounts:
          {{- end }}
          {{- if eq .Values.taskRunners.mode "internal" }}
            - name: {{ default "node-modules" .Values.main.persistence.volumeName }}
              mountPath: {{ .Values.main.persistence.mountPath }}
              {{- if .Values.main.persistence.subPath }}
              subPath: {{ .Values.main.persistence.subPath }}
              {{- end }}
              readOnly: false
          {{- end }}
          {{- if and .Values.nodes.external.packages (eq .Values.taskRunners.mode "internal") }}
            - name: community-node-modules
              mountPath: "/home/node/.n8n/nodes"
              readOnly: false
          {{- end }}
          {{- if eq (include "n8n.postgres.ssl.hasCA" .) "true" }}
            - name: pg-ssl-ca
              mountPath: /home/node/certs/ca/ca.crt
              subPath: ca.crt
              readOnly: true
          {{- end }}
          {{- if eq (include "n8n.postgres.ssl.hasCert" .) "true" }}
            - name: pg-ssl-cert
              mountPath: /home/node/certs/cert/cert.crt
              subPath: cert.crt
              readOnly: true
          {{- end }}
          {{- if eq (include "n8n.postgres.ssl.hasKey" .) "true" }}
            - name: pg-ssl-key
              mountPath: /home/node/certs/key/cert.key
              subPath: cert.key
              readOnly: true
          {{- end }}
          {{- with (default .Values.volumeMounts .Values.main.volumeMounts) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if eq .Values.taskRunners.mode "external" }}
        - name: {{ include "n8n.names.name" . }}-task-runners
          image: {{ include "n8n.images.image" (dict "imageRoot" .Values.taskRunners.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.taskRunners.image.pullPolicy }}
          command: ["/usr/local/bin/task-runner-launcher"]
          args: ["javascript", "python"]
          ports:
            - name: runner-http
              containerPort: {{ .Values.taskRunners.external.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: runner-http
          readinessProbe:
            httpGet:
              path: /healthz
              port: runner-http
          resources:
            {{- toYaml .Values.taskRunners.external.resources | nindent 12 }}
          env:
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "n8n.names.fullname" . }}-task-runners-secret
                  key: auth-token
          {{- include "n8n.runners.env" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "n8n.names.fullname" . }}-task-runners-configmap
          volumeMounts:
            - name: {{ default "node-modules" .Values.main.persistence.volumeName }}
              mountPath: {{ .Values.main.persistence.mountPath }}
              {{- if .Values.main.persistence.subPath }}
              subPath: {{ .Values.main.persistence.subPath }}
              {{- end }}
              readOnly: false
          {{- if .Values.nodes.external.packages }}
            - name: community-node-modules
              mountPath: "/home/node/.n8n/nodes"
              readOnly: false
          {{- end }}
      {{- end }}
      {{- with .Values.main.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq (include "n8n.main.hasVolumes" .) "true" }}
      volumes:
      {{- end }}
      {{- if .Values.nodes.external.packages }}
        - name: community-node-modules
          emptyDir: {}
      {{- end }}
      {{- if .Values.npmRegistry.enabled }}
        - name: npmrc
          secret:
            secretName: {{ default (printf "%s-npm-registry-secret" (include "n8n.names.fullname" .)) .Values.npmRegistry.secretName | quote }}
            optional: true
      {{- end }}
      {{- if eq (include "n8n.postgres.ssl.hasCA" .) "true" }}
        - name: pg-ssl-ca
          secret:
            secretName: {{ default (printf "%s-pg-ssl-ca" (include "n8n.names.fullname" .)) .Values.db.postgresdb.ssl.existingCertificateAuthorityFileSecret.name }}
            items:
              - key: {{ default "ca.crt" .Values.db.postgresdb.ssl.existingCertificateAuthorityFileSecret.key }}
                path: ca.crt
      {{- end }}
      {{- if eq (include "n8n.postgres.ssl.hasCert" .) "true" }}
        - name: pg-ssl-cert
          secret:
            secretName: {{ default (printf "%s-pg-ssl-cert" (include "n8n.names.fullname" .)) .Values.db.postgresdb.ssl.existingCertFileSecret.name }}
            items:
              - key: {{ default "cert.crt" .Values.db.postgresdb.ssl.existingCertFileSecret.key }}
                path: cert.crt
      {{- end }}
      {{- if eq (include "n8n.postgres.ssl.hasKey" .) "true" }}
        - name: pg-ssl-key
          secret:
            secretName: {{ default (printf "%s-pg-ssl-key" (include "n8n.names.fullname" .)) .Values.db.postgresdb.ssl.existingPrivateKeyFileSecret.name }}
            items:
              - key: {{ default "cert.key" .Values.db.postgresdb.ssl.existingPrivateKeyFileSecret.key }}
                path: cert.key
      {{- end }}
      {{- with (default .Values.volumes .Values.main.volumes) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.nodeSelector .Values.main.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.affinity .Values.main.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.tolerations .Values.main.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $dnsPolicy := coalesce .Values.main.dnsPolicy .Values.global.dnsPolicy "" }}
      {{- if $dnsPolicy }}
      dnsPolicy: {{ $dnsPolicy }}
      {{- end }}
      {{- with (default .Values.global.dnsConfig .Values.main.dnsConfig) }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ default "node-modules" .Values.main.persistence.volumeName }}
      spec:
        accessModes:
          - {{ .Values.main.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.main.persistence.size }}
        {{- if .Values.main.persistence.storageClass }}
          {{- if (eq "-" .Values.main.persistence.storageClass) }}
        storageClassName: ""
          {{- else }}
        storageClassName: {{ .Values.main.persistence.storageClass | quote }}
          {{- end }}
        {{- end }}
{{- end }}
